Vagrant.configure("2") do |config|

#Create Zabbix server
    config.vm.define "Z-serv1" do |zserv|
	zserv.vm.box = "sbeliakou/centos"
	zserv.vm.hostname = "Z-serv1"
	zserv.vm.network :private_network, ip: "172.22.22.22"
	zserv.vm.provider "virtualbox" do |vb|
	    vb.gui = false
	    vb.memory = "2048"
	    vb.name = "Z-serv1"
	end
	zserv.vm.provision :shell, :path => "zabbix.sh"
    end

#Create Nginx Tomcat ZAgent server
    config.vm.define "ntzserv1" do |ntz|
	ntz.vm.box = "sbeliakou/centos"
	ntz.vm.hostname = "ntzserv1"
	ntz.vm.network :private_network, ip: "172.22.22.23"
	ntz.vm.provider "virtualbox" do |vb|
	    vb.gui = false
	    vb.memory = "2048"
	    vb.name = "ntzserv1"
	end
	ntz.vm.provision :shell, :path => "ntz.sh"
    end
end